version: '3.9'

services:
  licenseserver:
    image: fabreguesm/flx-server-license:1.0.0
    networks:
      - traefik
    volumes:
      - 'node_data:/app/data/'
    deploy:
      placement:
        constraints: ["${NODE}"]
    environment:
      - PORT=9900
      - HOST=localhost
      - SECRET_KEY=p@55w0rdu1tr@s3cr3t0
      - DB=serverlicencia
      - DB_USERNAME=flexxus
      - TZ=-03:00
      - BASE_URL=http://10.250.0.68:5006
      - DB_HOST=mariadb
      - DB_PORT=3306     
      - DB_PASS=Flexxus2023**
      - DIAS_DESDE_DEMO=-1
      - DIAS_HASTA_DEMO=90
      - PRODUCTO_DEFECTO=API
      - VERSION_DEFECTO=Demo
      - CANTIDAD_DEFECTO_DEMO=10
      - CANTIDAD_DEFECTO=1
      - PATH_LICENCIAACTUALIZAR=v5/license/update
      - SECRET_API=53ru3r_d3_1iC3nci@s_u2
    ports:
      - "5006:9900"
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  
volumes:
  node_data:
    name: "${SERVICE_NAME}_node-data"
networks:
  traefik:
    external: 
      name: traefik
